# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: redhat_cop
name: vmware_ops
version: 0.0.1
readme: README.md
authors:
  - Ansible Cloud Content Team (@redhat-cop)
description: null
license_file: LICENSE
tags:
  - vmware
repository: https://github.com/redhat-cop/cloud.vmware_ops
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/redhat-cop/cloud.vmware_ops
issues: https://github.com/redhat-cop/cloud.vmware_ops/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
dependencies: {
  "vmware.vmware_rest": ">=2.3.1"
}
