- name: Gather storage policy
  community.vmware.vmware_vm_storage_policy_info:
    hostname: "{{ info_hostname }}"
    username: "{{ info_username }}"
    password: "{{ info_password }}"
    port: "{{ info_port | d(omit) }}"
    validate_certs: "{{ info_validate_certs }}"
  register: __storage_policy

- name: Create JSON file from fetched data
  ansible.builtin.copy:
    content: "{{ __storage_policy.spbm_profiles | to_json }}"
    dest: "{{ info_storage_file }}"
    mode: "0644"
